# Generated by Django 5.0.7 on 2024-07-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_actionlist_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionlist',
            table='actionlist',
        ),
    ]
