# Generated by Django 5.0.7 on 2024-07-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_actionlist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionlist',
            table='todo_actionlist',
        ),
    ]
