# Generated by Django 5.0.7 on 2024-07-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_actionlist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlist',
            options={'managed': True},
        ),
    ]
